apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nldoc
resources:
- sa.yaml
- deployments.yaml
- custom-workers.yaml
- folio-spec-worker-code.cm.yaml
- sse-bridge-code.cm.yaml
- document-source-shim-code.cm.yaml


